# Upstream 1: Landing Page (Next.js)
upstream incinera_landing_upstream {
    server incinera-web:3000;
    keepalive 32;
}

# Upstream 2: Torneios Frontend (Next.js PWA)
upstream intereng_web_upstream {
    server pwa-torneios-web:3001;
    keepalive 32;
}

# Upstream 3: Torneios Backend API (NestJS)
upstream intereng_api_upstream {
    server intereng-api:3000;
    keepalive 32;
}
